mv *.pkl log_files/ 2> /dev/null
mv *.csv log_files/ 2> /dev/null
mv *_plots log_files/ 2> /dev/null
mv simulation-step* data_files/ 2> /dev/null
mv mdff_template.namd data_files/ 2> /dev/null
mv 3jd8_cryst_altered-extrabonds-cis.txt data_files/ 2> /dev/null
mv 3jd8_cryst_altered-extrabonds-chi.txt data_files/ 2> /dev/null
mv 3jd8_cryst_altered-extrabonds.txt data_files/ 2> /dev/null
mv 3jd8_cryst_altered.pdb data_files/ 2> /dev/null
mv 3jd8_cryst_altered_autopsf*.* data_files/ 2> /dev/null
mv 3jd8_cryst_altered-grid.pdb data_files/ 2> /dev/null
mv emd_6640-grid.dx data_files/ 2> /dev/null
mv *.log log_files/ 2> /dev/null
mv *.tcl scripts/ 2> /dev/null
mv molpro.sh scripts/ 2> /dev/null
mv last_frame_ILE.pdb data_files/ 2> /dev/null
mv last_frame_his.pdb data_files/ 2> /dev/null
mv last_frame_OXT.pdb data_files/ 2> /dev/null
mv last_frame_bf.pdb data_files/ 2> /dev/null
mv last_frame_nohydro.pdb data_files/ 2> /dev/null
mv frame*.pdb data_files/ 2> /dev/null
mv clash_allframes.sh scripts/ 2> /dev/null
mv cleanup.sh scripts/ 2> /dev/null
mv *.png log_files/ 2> /dev/null
mv last_frame_real_space_refined_all_states.pdb data_files/ 2> /dev/null
mv ccc_*.txt data_files/ 2> /dev/null
mv CC_map_files.sh scripts/ 2> /dev/null
mv all_frames_clash.txt data_files/ 2> /dev/null
mv gnuplot*.sh scripts/ 2> /dev/null
mv phenix_rs.sh scripts/ 2> /dev/null
mv rosetta.sh scripts/ 2> /dev/null
mv rosetta_resi.sh scripts/ 2> /dev/null
mv sort_perResi_Score.sh scripts/ 2> /dev/null
mv *.sc log_files/ 2> /dev/null
mv *.geo log_files/ 2> /dev/null
mv log_files/namdinator_stdout.log . 2> /dev/null
